site_name: PacIFiC

theme:
  name: mkdocs
  custom_dir: 'theme1/'

docs_dir: pages

site_url: https://anthonywachs.github.io/pacific/
repo_url: https://gitlab.math.ubc.ca/PacIFiC-devel-team/PacIFiC/
repo_name: 'GitLab'
edit_uri: -/edit/master/docs/pages/


copyright: Footer text



nav: 
  - Features: 'features.md'
  - Examples: 'examples/index.md'
  - Documentation:
    - Grains: 'doxygen/grains/'
  - Gallery: 'gallery.md'
  - Download: 'download.md'
